#Auto generated by Edalize
TARGET        = riscv2
TOPLEVEL      = tb_risc_v2_top

VLOG_DEFINES  = 
VLOG_INCLUDES = 
GEN_PARAMS    = 

XELAB_OPTIONS =	-debug typical -initfile /home/cafecafe/Documents/OsvvmLibraries/Scripts/xsim.dir/xsim.ini
XSIM_OPTIONS  = -wdb riscv2.wdb -tclbatch xsim_cfg.tcl